#9 raise FileNotFoundError if a tif file is missing in preprocess_single instead of error AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'